# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
loader_version=0.18.4
# Mod Properties
mod_version=1.0
maven_group=com.papack
archives_base_name=BootsLunge-fabric1.21.11
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.141.2+1.21.11
# Mod Menu
modmenu_version=17.0.0